export const iniValues= {
  firstName: "",
  lastName: "",
  email: "",
  nationalId: "",
  address: "",
  phone: "",
  acceptedPrivacyPolicy: false,
  state: "",
  city: "",
  district: "",
  datePurchased: "",
  orderNumber : "",
  adquiredGood : "",
  adquiredDescription : "",
  reclaimedAmount : "",
  claimDetail : "",
  complainDetail : "",
  customerOrder : "",
  tutorFirstName: "",
  tutorLastName: "",
  tutorNationalId: "",
  tutorEmail: "",
  tutorPhone: "",
  tutorAddress: "",
  tutorState: "",
  tutorCity: "",
  tutorDistrict: "",
}